// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WpfApp2.ConsoleApp20_08_2024;

namespace WpfApp2.ConsoleApp20_08_2024.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WpfApp2.ConsoleApp20_08_2024.Enities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int?>("CurrentUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("CurrentUserId")
                        .IsUnique()
                        .HasFilter("[CurrentUserId] IS NOT NULL");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("WpfApp2.ConsoleApp20_08_2024.Enities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("MainUser");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDay = new DateTime(2024, 8, 27, 7, 1, 27, 398, DateTimeKind.Utc).AddTicks(5852),
                            Email = "1@mail.ru",
                            Name = "Vlad",
                            Password = "12345"
                        },
                        new
                        {
                            Id = 2,
                            BirthDay = new DateTime(2024, 8, 27, 7, 1, 27, 398, DateTimeKind.Utc).AddTicks(5852),
                            Email = "2@mail.ru",
                            Name = "Alex",
                            Password = "12345"
                        },
                        new
                        {
                            Id = 3,
                            BirthDay = new DateTime(2024, 8, 27, 7, 1, 27, 398, DateTimeKind.Utc).AddTicks(5852),
                            Email = "3@mail.ru",
                            Name = "Kirill",
                            Password = "12345"
                        },
                        new
                        {
                            Id = 4,
                            BirthDay = new DateTime(2024, 8, 27, 7, 1, 27, 398, DateTimeKind.Utc).AddTicks(5852),
                            Email = "4@mail.ru",
                            Name = "Kostya",
                            Password = "12345"
                        },
                        new
                        {
                            Id = 5,
                            BirthDay = new DateTime(2024, 8, 27, 7, 1, 27, 398, DateTimeKind.Utc).AddTicks(5852),
                            Email = "5@mail.ru",
                            Name = "Klim",
                            Password = "12345"
                        });
                });

            modelBuilder.Entity("WpfApp2.ConsoleApp20_08_2024.Enities.UserAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("WpfApp2.ConsoleApp20_08_2024.Enities.Book", b =>
                {
                    b.HasOne("WpfApp2.ConsoleApp20_08_2024.Enities.User", "CurrentUser")
                        .WithOne("Book")
                        .HasForeignKey("WpfApp2.ConsoleApp20_08_2024.Enities.Book", "CurrentUserId");
                });
#pragma warning restore 612, 618
        }
    }
}
